#!/bin/sh

# -------- Autostart -------
export SXHKD_SHELL='/bin/sh'
killall -9 picom
killall -9 sxhkd
# killall -9 plasmashell
sxhkd &
picom -b --config $HOME/.config/picom/picom.conf &
bspc config border_width         2
bspc config window_gap          12
bspc config top_padding          0
bspc config bottom_padding       0

$HOME/.config/polybar/launch.sh &
$HOME/.fehbg

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ulauncher manage=off border=off
bspc rule -a albert border=off
bspc rule -a Zathura state=tiled

bspc config normal_border_color "#484848"
bspc config focused_border_color "#928374"
bspc config urgent_border_color "#F92672"
bspc config presel_border_color "#A4E400"
bspc config presel_feedback_color "#62D8F1"


# bspc rule -a dropdown sticky=on state=floating hidden=on
# kitty --class dropdown -e "zsh -i" &


bspc rule -a plasmashell sticky=on layer=above state=floating


killall plasmashell
