#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0

yabai -m config window_shadow                float
yabai -m config window_animation_duration    0.15

# border
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config insert_feedback_color        0xffa4e400 # selected
yabai -m config normal_window_border_color   0xff505050
yabai -m config active_window_border_color   0xfff92672 # focused

# window opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   10

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap


# Rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Finder$" title="Info$" manage=off
yabai -m rule --add app="^Finder$" title="Copy$" manage=off
yabai -m rule --add app="^Finder$" title="^Connect to Server$" manage=off
yabai -m rule --add app="^Finder$" title="^Connecting to Server$" manage=off
yabai -m rule --add title="Preferences$" manage=off
yabai -m rule --add app="^NetAuthAgent$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^Battle.net$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on
yabai -m rule --add app="LuLu" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="^PrinterProxy$" manage=off
yabai -m rule --add app="^Calendar$" title="^$" manage=off
yabai -m rule --add title="Keeper Desktop Applet" manage=off
yabai -m rule --add title="Microsoft Teams Notification" manage=off
yabai -m rule --add title="Microsoft Teams Notification" manage=off
# yabai -m rule --add title="\| Microsoft Teams" can_size=false manage=off

yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

# setleds ^caps > /dev/null

echo "yabai configuration loaded.."
